<Project Sdk="Microsoft.NET.Sdk.Razor">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CashPrism.Application\CashPrism.Application.csproj" />
    <ProjectReference Include="..\CashPrism.Domain\CashPrism.Domain.csproj" />
  </ItemGroup>

</Project>
