<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CashPrism.Application\CashPrism.Application.csproj" />
    <ProjectReference Include="..\CashPrism.Domain\CashPrism.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
  </ItemGroup>

</Project>
