// <auto-generated />
using System;
using CashPrism.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CashPrism.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CashPrismDbContext))]
    partial class CashPrismDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CashPrism.Domain.Access.Credential", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SetAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Credentials", (string)null);
                });

            modelBuilder.Entity("CashPrism.Domain.Bookings.Booking", b =>
                {
                    b.Property<string>("Fingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("AmountInCents")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractInterval")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Counterparty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CounterpartyAccount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsContract")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExcludedFromDisposableIncome")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTransfer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MandateReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ReportedBalanceInCents")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SourceImportRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SplitRole")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionKind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Fingerprint");

                    b.HasIndex("SourceImportRunId");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("CashPrism.Domain.Imports.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BookingsInserted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookingsUnchanged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookingsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ExportedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FileHash");

                    b.ToTable("ImportRuns", (string)null);
                });

            modelBuilder.Entity("CashPrism.Domain.Imports.RawRow", b =>
                {
                    b.Property<Guid>("ImportRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImportRunId", "Fingerprint");

                    b.ToTable("RawRows", (string)null);
                });

            modelBuilder.Entity("CashPrism.Domain.Imports.RawRow", b =>
                {
                    b.HasOne("CashPrism.Domain.Imports.ImportRun", null)
                        .WithMany()
                        .HasForeignKey("ImportRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
